_BASE_: "Base-Panoptic-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  META_ARCHITECTURE: "PanopticFPN"
  RESNETS:
    DEPTH: 50
  SEM_SEG_HEAD:
    NAME: "SemSegFPNHead_DFConv"
    LOSS_WEIGHT: 0.3
SOLVER:
  STEPS: (121000, 161000)
  MAX_ITER: 181000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
