_BASE_: "Base-Panoptic-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  META_ARCHITECTURE: "PanopticFPN"
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (61000, 81000)
  MAX_ITER: 91000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
